version: '3.3'

networks:
  vpcbrEX2:
    ipam:
     driver: default
     config:
        - subnet: 10.18.0.0/24

services:
  blockscout:
    image: blockscout/blockscout-core:3.7.4-pre-4
    container_name: blockscout
    environment:
      DATABASE_URL: "postgresql://postgres:secret@postgres:5432/poa_dev?ssl=false"
      ETHEREUM_JSONRPC_HTTP_URL: http://dev.arkdia.co:8545/
      ETHEREUM_JSONRPC_TRACE_URL: http://dev.arkdia.co:8545/
      ETHEREUM_JSONRPC_VARIANT: besu
      LOGO: /images/blocks.svg
      COIN: "ARK"
      COIN_NAME: "Arkdia"
      PORT: 4000
    #volumes:
      #- ./data/images:/opt/app/apps/block_scout_web/assets/static/images/
    ports:
      - "4000:4000"
    networks:
      vpcbrEX2:
        ipv4_address: 10.18.0.10


  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: poa_dev
    networks:
      vpcbrEX2:
        ipv4_address: 10.18.0.11
